#!/usr/bin/env bash

Var=$PWD/var

prep() { gawk --source '
/^function[ \t]+[A-Z]/ { 
    tmp = gensub(/(function[ \t]+)([A-Za-z0-9_]+).([^,\)]+).*/,
                 "\\2,\\3","g",$0)
    split(tmp,cs,",")
    class = cs[1]
    self  = cs[2]
    }
/^[ \t]+isa/ { 
    $0 = gensub(/^([ \t]+)isa.[ \t]*([A-Za-z0-9_]+)(.*)/,
               "\\1isa(" self ", \"" class "\", \"\\2\", \\2\\3","g",$0)
    }
    { $0 = gensub(/\.([^0-9])([a-zA-Z0-9_]*)/,
	         "[\"\\1\\2\"]","g",$0) 
      $0 = gensub(/__/,".","g",$0) 
      print 
    } 
' -
}
for i in *.awk; do
  	if [ "$i" -nt "$Var/$i" ]; then
     		cat $i | prep > $Var/$i
  	fi
done

f=$1
shift
if [ -f "$f" ]; then
	AWKPATH="$Var" gawk -v Main="$(basename $f)" --source "`cat $f | prep`"   "$@"
elif [ "$f" == "hi" ]; then
  	git pull
elif [ "$f" == "bye" ]; then
  	git commit -am "pushing"
  	git push
  	git status
fi
